INSERT INTO STUDENT (NAME, AGE, DEPARTMENT) VALUES ('John', 22, 'CS');
INSERT INTO STUDENT (NAME, AGE, DEPARTMENT) VALUES ('Alice', 25, 'IT');
INSERT INTO STUDENT (NAME, AGE, DEPARTMENT) VALUES ('Bob', 28, 'CS');
INSERT INTO STUDENT (NAME, AGE, DEPARTMENT) VALUES ('Emma', 21, 'ECE');